config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  post "/add_item", to: "home#add_item"
  get "/cart", to: "home#cart"

  resources :home, only: [:index]
  resources :orders do
    collection do
      post :notify 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product

  def self.total_price(cart_items)
    cart_items.sum { |item| item.product.unit_price * item.quantity }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end

  def add_item
    product = Product.find(params[:product_id])

    @cart_item = CartItem.find_or_initialize_by(product: product)
    @cart_item.quantity += params[:quantity].to_i
    if @cart_item.save
      redirect_to root_path, notice: '商品已加入購物車'
    else
      redirect_to root_path, alert: '無法加入購物車'
    end
  end

  def cart
    @cart_items = CartItem.includes(:product).order(updated_at: :desc)
    @total_price = CartItem.total_price(@cart_items)
    @item_desc = CartItem.all.map { |item| "#{item.product.name} x #{item.quantity}" }.join(" ; ")

    @form_info = Newebpay.new.form_info
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:notify]

  def notify
    response = NewebpayResponse.new(params[:TradeInfo]).response

    if response["Status"] != "SUCCESS"
      redirect_to root_path, notice: '付款失敗'
    else
      response = response["Result"]
      Order.create!(order_number: response["MerchantOrderNo"], total_price: response["Amt"])
      order = Order.find_by(order_number: response["MerchantOrderNo"])
      @cart_items = CartItem.all
      @cart_items.each do |cart_item|
        OrderItem.create!(
          order: order,
          product_name: cart_item.product.name,
          product_quantity: cart_item.quantity,
          unit_price: cart_item.product.unit_price,
          subtotal_price: cart_item.quantity * cart_item.product.unit_price
        )
      end
      @cart_items.destroy_all
      redirect_to root_path, notice: '付款成功，訂單已建立'
    end
    rescue ActiveRecord::RecordInvalid => e
      redirect_to root_path, alert: "訂單建立失敗: #{e.message}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/cart.html.erb
<div class="container text-center m-5">
  <div class="col-6 p-3 border m-auto">
    <h2>購物車</h2>
      <table class="table table-bordered">
        <thead>
          <tr class="table-secondary">
            <td>產品名稱</td>
            <td>產品單價</td>
            <td>產品數量</td>
            <td>小計</td>
          </tr>
        </thead>
        <% @cart_items.each do |item| %>
          <tbody>
            <tr>
              <td><%= item.product.name %></td>
              <td><%= item.product.unit_price %></td>
              <td><%= item.quantity %></td>
              <td class="text-end"><%= item.product.unit_price * item.quantity %></td>
            </tr>
          </tbody>
        <% end %>
        <tfoot>
          <tr>
            <td colspan="3" class="table-success">總價</td>
            <td class="text-end"><%= @total_price %></td>
          </tr>
        </tfoot>
      </table>
      <%= form_with(url: 'https://ccore.newebpay.com/MPG/mpg_gateway', method: "post") do |form| %>
        <input type="hidden" id="MerchantID" name="MerchantID" value="<%= @form_info[:MerchantID] %>">
        <input type="hidden" id="TradeInfo" name="TradeInfo" value="<%= @form_info[:TradeInfo] %>">
        <input type="hidden" id="TradeSha" name="TradeSha" value="<%= @form_info[:TradeSha] %>">
        <input type="hidden" id="Version" name="Version" value="<%= @form_info[:Version] %>">
        <%= form.submit "結帳" %>
      <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container text-center m-5">
  <div class="col-6 p-3 border m-auto">
    <h2>商品列表</h2>
    <div class="text-end"><%= link_to "購物車", cart_path %></div>
    <% @products.each do |product| %>
    <div class="border p-3">
      <p>商品名稱：<%= product.name %></p>
      <p>商品描述：<%= product.description %></p>
      <p>商品單價：<%= product.unit_price %>元</p>
      <form action="<%= add_item_path %>" method="post">
        <label for="quantity">數量：</label>
        <input type="hidden" name="product_id" value="<%= product.id %>">
        <input type="number" id="quantity" name="quantity" min="1" max="999" value="1" class="text-center">
        <button type="submit">加入購物車</button>
      </form>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommercePlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>